CREATE TABLE db_Churn.prod_Churn (
    Customer_ID VARCHAR(50) PRIMARY KEY,
    Gender VARCHAR(20),
    Age INT,
    Married VARCHAR(10),
    State VARCHAR(50),
    Number_of_Referrals INT,
    Tenure_in_Months INT,
    Value_Deal VARCHAR(50),
    Phone_Service VARCHAR(10),
    Multiple_Lines VARCHAR(10),
    Internet_Service VARCHAR(20),
    Internet_Type VARCHAR(50),
    Online_Security VARCHAR(10),
    Online_Backup VARCHAR(10),
    Device_Protection_Plan VARCHAR(10),
    Premium_Support VARCHAR(10),
    Streaming_TV VARCHAR(10),
    Streaming_Movies VARCHAR(10),
    Streaming_Music VARCHAR(10),
    Unlimited_Data VARCHAR(10),
    Contract VARCHAR(20),
    Paperless_Billing VARCHAR(10),
    Payment_Method VARCHAR(50),
    Monthly_Charge DECIMAL(10,2),
    Total_Charges DECIMAL(10,2),
    Total_Refunds DECIMAL(10,2),
    Total_Extra_Data_Charges DECIMAL(10,2),
    Total_Long_Distance_Charges DECIMAL(10,2),
    Total_Revenue DECIMAL(10,2),
    Customer_Status VARCHAR(20),
    Churn_Category VARCHAR(50),
    Churn_Reason VARCHAR(255)
);




INSERT INTO db_Churn.prod_Churn (
    Customer_ID,
    Gender,
    Age,
    Married,
    State,
    Number_of_Referrals,
    Tenure_in_Months,
    Value_Deal,
    Phone_Service,
    Multiple_Lines,
    Internet_Service,
    Internet_Type,
    Online_Security,
    Online_Backup,
    Device_Protection_Plan,
    Premium_Support,
    Streaming_TV,
    Streaming_Movies,
    Streaming_Music,
    Unlimited_Data,
    Contract,
    Paperless_Billing,
    Payment_Method,
    Monthly_Charge,
    Total_Charges,
    Total_Refunds,
    Total_Extra_Data_Charges,
    Total_Long_Distance_Charges,
    Total_Revenue,
    Customer_Status,
    Churn_Category,
    Churn_Reason
)
SELECT 
    Customer_ID,
    Gender,
    Age,
    Married,
    State,
    Number_of_Referrals,
    Tenure_in_Months,
    -- Convert empty strings ('') to NULL, then replace NULL with 'None'
    COALESCE(NULLIF(Value_Deal, ''), 'None'),
    Phone_Service,
    COALESCE(NULLIF(Multiple_Lines, ''), 'No'),
    Internet_Service,
    COALESCE(NULLIF(Internet_Type, ''), 'None'),
    COALESCE(NULLIF(Online_Security, ''), 'No'),
    COALESCE(NULLIF(Online_Backup, ''), 'No'),
    COALESCE(NULLIF(Device_Protection_Plan, ''), 'No'),
    COALESCE(NULLIF(Premium_Support, ''), 'No'),
    COALESCE(NULLIF(Streaming_TV, ''), 'No'),
    COALESCE(NULLIF(Streaming_Movies, ''), 'No'),
    COALESCE(NULLIF(Streaming_Music, ''), 'No'),
    COALESCE(NULLIF(Unlimited_Data, ''), 'No'),
    Contract,
    Paperless_Billing,
    Payment_Method,
    Monthly_Charge,
    Total_Charges,
    Total_Refunds,
    Total_Extra_Data_Charges,
    Total_Long_Distance_Charges,
    Total_Revenue,
    Customer_Status,
    COALESCE(NULLIF(Churn_Category, ''), 'Others'),
    COALESCE(NULLIF(Churn_Reason, ''), 'Others')
FROM db_Churn.stg_Churn;

